sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KvAaGQ3oMmqGxgPnGXnNdQPTRWY5xZWYJ7lnwMlnB4Rbh3dis3LqIPgPrF0b75jfZoh76NodFK0EQv/kF4Kgexd+de3AQqOKseIZ/Lk5ezZeWmfHZBltroflwWKl5f3iDoCk8FAhEAPDpNKp9Kve6LZ+PNjrkxvoLaudzFOr/y2fkRmtuOHoIwm/iOUIk413AI05Cbd0jsUSqzWLdnpmKjT29PhiXdcxnmwug9zXv03LpvYPBN8T0INvzz7Bn+AyBAu8wDb9CEitRIXnZs9E6WtR+UYa2zYSNYSvgHh2oIm1HpUXAp+hpbih9Eys3c8CgpHDuSjqg3lQnvK/hUl0HSEr+FMunX6wyeJUUiWzsg8CGavqLgaXXA4jGRN1W189OXNcC3x19hXUN+89f0v4UXtk8sARVJYzNIm8aj9Btb9d7GhmjIRFZRgaJXWf035LWSG1+MJA4L5gLTQQ2/pjM1Nd3VNXiBFm0cvyJjSGXEl8ett2loWgHwiAsBVbFkb0DFecD1Pq3gi+G5RoUXZrBiUmUYESukITVhdgfSWyRN84S3zCrIU5eKkjR9lw/kq/ES9sznfD2kSD9fozvUdA9YzzNrq8Jp7/XmfX4p38ereUiCRyPA921OV2lQ0rJFHCC0I04sNtX/XXjDjQAxVtRC0086YCR5EqLJl35RGkkhs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Circus-Boys-on-the-Mississippi-Or-Afloat-with-the-Big-Show-on-the-Big-River_2477
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy